version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "mambaforge-23.11"
conda:
    environment: doc/readthedocs-env.yml
python:
    install:
        - method: pip
          path: .
submodules:
    include: all
    recursive: true
