#:schema https://www.schemastore.org/prek.json

minimum_prek_version = "0.3.8"

exclude = "(?:^extern/)"

[[repos]]
repo = "builtin"
hooks = [
  {
    id = "end-of-file-fixer",
    exclude = '''
(?x)^(
  ^.*\.ai|
  ^.*\.txt\
  ^extern/
)
'''
  },
  {
    id = "trailing-whitespace",
    exclude = '''
(?x)^(
  ^.*\.ai|
  ^.*\.txt|
  ^extern/|
  ^setup.cfg
)
'''
  },
  { id = "check-executables-have-shebangs" },
  { id = "check-json" },
  { id = "check-toml" },
  {
    id = "check-yaml",
    exclude = '\.clang-format'
  },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending" },
  { id = "check-added-large-files" },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-vcs-permalinks" },
  { id = "check-shebang-scripts-are-executable" },
  { id = "check-illegal-windows-names" },
]

[[repos]]
repo = "https://github.com/glotzerlab/fix-license-header"
rev = "96a6da2d22354ecb4dbc50809e9455c7f1e20fe8"  # frozen: v0.4.1
hooks = [
  {
    id = "fix-license-header",
    name = "Fix License Headers (Python)",
    exclude = """
(?x)(
    ^doc/|
    ^extern/
    )
""",
    types_or = [
      "c",
      "c++",
      "python"
    ],
    args = [
      "--license-file=LICENSE",
      "--start=2",
      "--num=1",
      "--add=This file is from the freud project, released under the BSD 3-Clause License.",
      "--keep-before=#!"
    ]
  }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "2eeb5678de71a00c0902cbda7105d328432f72cb"  # frozen: v0.16.8
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check" }
]

[[repos]]
repo = "https://github.com/cheshirekow/cmake-format-precommit"
rev = "e2c2116d86a80e72e7146a06e68b7c228afc6319"  # frozen: v0.6.13
hooks = [
  { id = "cmake-format" }
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-clang-format"
rev = "e2b496dc2bd8340c2524cb9a2d2a943cde1bb6df"  # frozen: v23.1.1
hooks = [
  {
    id = "clang-format",
    types_or = [
      "c",
      "c++"
    ]
  }
]

[[repos]]
repo = "https://github.com/mit-d/check-unicode"
rev = "9d217f6f91d9e2de6bc31b54575ff35e595173f5"  # frozen: v0.6.0
hooks = [
  { id = "check-unicode",
    args = [
      "--allow-printable",
      "--check-confusables",
    ]
  }
]
