name: Feature Request
description: Suggest a new feature for freud
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Description
      description: What new feature would be useful to add to freud?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: How should this new feature be implemented? What should a script using this feature look like?
    validations:
      required: true
  - type: textarea
    attributes:
        label: Additional Context
        description: What additional information is useful to understand this request?
  - type: markdown
    attributes:
      value: |
        We would welcome your contribution!

        If you plan to implement this functionality, the freud developers will discuss the
        proposed design and API with you **before** you begin work.
