set(locality_sources
    locality/AABBQuery.cc
    locality/FilterRAD.cc
    locality/FilterSANN.cc
    locality/LinkCell.cc
    locality/NeighborComputeFunctional.cc
    locality/NeighborList.cc
    locality/PeriodicBuffer.cc
    locality/Voronoi.cc
    )

set(locality_headers
    locality/AABB.h
    locality/AABBQuery.h
    locality/AABBTree.h
    locality/BondHistogramCompute.h
    locality/Filter.h
    locality/FilterRAD.h
    locality/FilterSANN.h
    locality/LinkCell.h
    locality/NeighborBond.h
    locality/NeighborList.h
    localty/NeighborPerPointIterator.h
    locality/NeighborQuery.h
    locality/PeriodicBuffer.h
    locality/RawPoints.h
    locality/Voronoi.h
    )
